---
- name: Install and Start Nginx on RHEL/CentOS
  hosts: target_hosts
  become: yes
  tasks:
    - name: Install Nginx
      yum:
        name: nginx
        state: present

    - name: Ensure Nginx is started and enabled
      service:
        name: nginx
        state: started
        enabled: yes
